[project]
name = "Philote-Cpp"
version = "0.1.0"
num_threads = 0

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/chrislupp/Philote-Cpp/"
git_default_branch = "main"

[paths]
compile_commands = "build/compile_commands.json"
output_dir = "docs/hdoc-output"

[includes]
use_system_includes = false
paths = ["Philote"]


[pages]
homepage = "docs/index.md"
paths = [
    "docs/pages/Basic Discipline.md",
    "docs/pages/Explicit Discipline.md",
    "docs/pages/Implicit Discipline.md",
    # Other paths as needed
]
