[project]
name = "Philote-Cpp"
version = "0.1.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/chrislupp/Philote-Cpp/"
git_default_branch = "main"

[paths]
compile_commands = "build/compile_commands.json"