name: Build and Regression Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  release_build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Eigen
      run: git clone https://gitlab.com/libeigen/eigen.git
      working-directory: ${{github.workspace}}

    - name: Configure PhiloteCpp
      run: cmake ..
      working-directory: ${{github.workspace}}/build

    - name: Build PhiloteCpp
      run: make
      working-directory: ${{github.workspace}}/build
