name: Build and Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
      strategy:
        matrix:
          os: [ubuntu-22.04]
          compiler: [
            {c: gcc-9, cpp: g++-9},
            {c: gcc-10, cpp: g++-10},
            {c: gcc-11, cpp: g++-11},
            {c: gcc-12, cpp: g++-12},
            {c: clang-12, cpp: clang++-12},
            {c: clang-13, cpp: clang++-13},
            {c: clang-14, cpp: clang++-14},
            {c: clang-15, cpp: clang++-15}
            ]
          build_type: [Debug, Release]
          # exclude:
          #   - os: macos-latest
          #     compiler: {c: gcc-9, cpp: g++-9}
          #     environment: Debug
          #   - os: macos-latest
          #     compiler: {c: gcc-9, cpp: g++-9}
          #     environment: Release
          #   - os: macos-latest
          #     compiler: {c: gcc-10, cpp: g++-10}
          #     environment: Debug
          #   - os: macos-latest
          #     compiler: {c: gcc-10, cpp: g++-10}
          #     environment: Release
          #   - os: macos-latest
          #     compiler: {c: clang-12, cpp: clang++-12}
          #     environment: Debug
          #   - os: macos-latest
          #     compiler: {c: clang-12, cpp: clang++-12}
          #     environment: Release
          #   - os: macos-latest
          #     compiler: {c: clang-13, cpp: clang++-13}
          #     environment: Debug
          #   - os: macos-latest
          #     compiler: {c: clang-13, cpp: clang++-13}
          #     environment: Release
            # - os: ubuntu-22.04
            #   compiler: {c: clang-15, cpp: clang++-15}
            #   environment: Debug
            # - os: ubuntu-22.04
            #   compiler: {c: clang-15, cpp: clang++-15}
            #   environment: Release
            
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v2
      
      - name: Prepare Build
        run: mkdir build
        working-directory: ${{github.workspace}}

      - name: Configure PhiloteCpp
        run: cmake .. -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        working-directory: ${{github.workspace}}/build

      - name: Build PhiloteCpp
        run: make
        working-directory: ${{github.workspace}}/build
